INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amoxicilina','cap.250 e 500 mg; xp','AMOX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Azitromicina','cp 500 mg cp; xp','ZYTROMAX ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ciprofloxacina ','cp 500 mg','QUINOX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cefuroxima ','cp 500 mg; xp','ZOREF');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Claritromicina ','cp 250 mg; 500 mg; xp','KLACID');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amoxicilina+acido clavulanico','xp; cp 500 mg; ampolas ','CLAVEPEN/CLAVAMOX ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Flucloxacilina ','xp; cap 500 mg; ampolas','FLOXAPEN/FLOXIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Espectinomicina','ampolas 2 gramas','TROBICIN /KIRIM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Eritromicina ','cp 500 mg; xp','ERITRAZON ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cotrimoxazol','cp 480 mg; cp 960 mg; xp','BACTRIM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nitrofurantoina ','cp 100 mg','FURADANTINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Norfloxacina ','cp 400 mg','BESFLOX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clindamicina ','cp 150 mg','DALACIN C ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clindamicina ','creme vaginal','DALACIN V');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Aciclovir ','cp 200 mg; cp 400 mg; cp 800 mg; pomada oftalmica','ECOZEN/ZOVIRAX/CICLOVIRAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Albendazol ','cp 400 m; xp ','ZENTEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Mebendazol ','cp 100 mg ; xp ','PANTELMIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Praziquantel ','cp 600 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tinidazol ','cp 500 mg','FASIGYN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Scnidazol ','cp 500 mg','FLAGENTYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pirantel ','xp 50 mg','COMBANTRIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloroquina ','cp 250 mg ','RESOCHINA ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Mefloquina ','cp 250 mg','MEFLOQUIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloroquina','cp 250 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Griseofulvina ','cp 125 mg; cp 500 mg','FULCIN /GRISOVIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Itraconazol','cp 100 mg','FUNGONAX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clotrimazol','creme dermico 1%','CANESTEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clotrimazol','1% creme ginecologco','GYNO-CLOTRIN/GINO-CANESTEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clotrimazol','ovulos vaginais','NALBIX/GINO-CANESTEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clotrimazol','spray dermico','CANESTEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cetoconazol ','creme; cp 200 mg; shampoo','KANAZOL/NIZORAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sulfureto de selenio','shampoo','SELENIX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nitrato de econazol ','creme; locao ; pó','PEVARYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tioconazol ','creme dermico ; solucao ungueal','TROSYD');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('lodopovidona ','solucao vaginal; solucao dermitologica; pomada; colutor','BETADINE/DIODYNE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metronidazol','ovulos 500 mg','FLAGYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Promestrieno ','cap vaginal 10 mg; creme vaginal','COLPOTROPHINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nitrato de Miconazol','creme','MICOZEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Policresuleno','ovulos vaginais; locao','NELEX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Estriol','creme vaginal','PAUSIGIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tamsulosina','cp 0,4 microg','OMNIC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Alprostadil ','10 micrg; 20 micrg ampolas','CAVERJECT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Finasterida','cp 5 mg','PROSCAR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloridrato de flavoxato','cp 200 mg','URISPAS');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Piracetam','cp 1200 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tibolona','cp 2,5 mg','LIVIAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carbidopa +levodopa','cp 25/100 mg; 25/ 250 mg','SINEMET');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Bicalutamida','cp 50 mg','CASODEX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Goserrelina','implante 10,8 mg','ZOLADEX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metilergometrina','cp 0,12mg ','METERGIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tiamazol','cp 5 mg ; cp 10 mg','METIBASOL/STRUMAZOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Propiltiouracilo','cp 50 mg','PROPYCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Levotiroxina','cp 100 micro','LETTER');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Medroxiprogesterona','cp 5 mg','PROVERA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Bromocriptina','cp 2,5 mg','PARLODEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acetato de noretisterona','cp 10 mg','PRIMOLUT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Citrato de clomifeno','cp 50 mg','DUFINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Azatioprina','cp 25 mg','IMURAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Progesterona','cp 100 mg','UTROGESTAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido acetilsalicilico +vit c','cp 150 mg','ASPIN INFANTIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido acetilsalicilico','cp 500 mg','ASPIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acetilsalicilato de lisina ','carteiras 500 mg; ampolas ','ASPEGIC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Paracetamol','cp 500 mg; xp; sup; 125 mg; 250 mg; 1000 mg; eferv','PANADOL / DAFALGAN / BEM-U-ROM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Beta-histina','cp 16 mg','BETASERC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acetilcisteina','carteiras 200 mg; cp 600 mg','FLUIMUCIL ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diclofenac ','cp 50 mg; 100 mg cap; suposit 100 mg; ampolas; gel','DOLACEN/ VOLTAREN / BIOFENAC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ibuprofeno','xp; cp 200 mg; cp 400 mg; carteiras','BRUFEN / DOLOMATE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Indometacina','cap 25 mg; suposit 100 mg','REUMACID/ INACID ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Etofenamato ','gel; creme;','REUMON GEL/INALGIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Naproxeno ','cp 250 mg; cp 500 mg; supos 250 mg; 500 mg','REUXEN/NAPROXIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pentoxiflina','cp 400 mg','TRENTAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metamizol','cp 575 mg','NOLOTIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tiocolquicosido ','cp 4 mg; ampolas','RELMUS');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Piroxicam','cp 20 mg','REUMOXICAM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diosmina','cp 450 mg','DAFLON/VENAFLON/DIOSMIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Glucosamina','ampol. 400 mg/3ml; po 1500 mg; cap 250 mg','VIARTRIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido fusidico','pomada','NADICLOX / FUCIDINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pivalato fluocortolona+lidocaina ','suposito ','ULTRAPROCT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidrocortisona+fenilefrinadrina+lidoc+tetra. ','pomada','ANUCET');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Messalazina','cp 500 mg','CLAVERSAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('D initrato isossorbida ','cp 5 mg; cp 20 mg','FLINDIX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Mononitrato isossorbida','cp 60 mg','IMDUR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Furosemida ','cp 40 mg; ampolas','LASIX/NAQUA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Espironolactona ','cp 25 mg; cp 100 mg','ALDACTONE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidroclorotiazida','cp 25 mg','HCT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Indapamida','cp 2,5 mg','FLUIDEMA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nitroglicerina','5 mg pensos transdermimicos','NITRODERM TTS-5');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nitroglicerina','10 mg pensos transdermimicos','NITRODERM TTS-10');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metildopa',' cp 250 mg','ALDOMET');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metildopa',' cp 500 mg','ALDOMET FORTE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ticlopidina',' cp 250 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Trimetazidina','cp 20 mg','VASTAREL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Propranolol','cp 10 mg; cp 40 mg','INDERAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Telmisartan','cp 40 mg','PRITOR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Telmisartan','cp 80 mg','PRITOR PLUS ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Valsartan','cp 80 mg; cp 160 mg','TAREG/DIOVAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Valsartan 80 mg +hidroclorotiazida','cp 12,5 mg','CO-TAREG/CO-DIOVAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Valsartan 160 mg +hidroclorotiazida','cp 12,5 mg','CO-TAREG/CO-DIOVAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amiodarona','cp 200 mg','CORDARONE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diltiazem','cp 180 mg','DILFAR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diltiazem','cp 200 mg','DILTIEM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nifedipina','cp 20 mg','ANGIPINA/ ADALAT AP');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nifedipina','cp 30 mg','ADALAT CR 30');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nifedipina',' cp 60 mg','ADALAT CR 60');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Captopril',' cp 25 mg','HIPOTENSIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Irbesartan','cp 30 mg ','APROVEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amlodipina','cp 5 mg; 10 mg','NORVASC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Atenolol ','cp 50 mg; 100 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido acetilsalicilico','cp 100 mg','ASPIRINA GR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido acetilsalicilico','cp 100 mg','CORIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido acetilsalicilico','cp 150 mg','TROMALYT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Bisoprolol ','cp 5 mg ; cp 10 mg','CONCOR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lisinopril ','cp 10 mg; 20 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carvedilol','cp 6,25; cp 25 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metoprolol','cp 100 mg','LOPRESOR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pravastatina','cp 20 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sinvastatina','cp 20 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clopidogrel','cp 75 mg','PLAVIX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dipiridamol','cp 75 mg','PERSANTIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acenocumarol','cp 4 mg','SINTRON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Varfarina','cp 5 mg','VARFINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Digoxina ','cp 0,25 mg; xp','LANOXIN ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Magnesio','solucao oral','MAGNESONA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Brometo ipratropio','20 micrg inalac.oral','ATROVENT PA ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Brometo ipratropio','inalac.nasal','ATROVENT UNIDOSE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Betametasona','solucao oral','CELESTONE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Betametasona','ampolas 14 mg/2m1','DIPROFOS DEPOT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Propionato clebetasol ','creme; pomada; solucao','DERMOVATE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Calcipotriol','creme','DAIVONEX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Suspensao oral lisados polibacterianos ','adulto; infantil ','LANTINGEN B ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lisados polibacterianos liofilizado','carteiras; cap inf; solug inf','BRONCHO-VAXON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lisados polibacterianos liofilizado','capsulas adulto','BRONCHO-VAXON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cetirizina ','cp; xp','ZYRTEC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Loratadina ','xp; cp','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Iclontelucaste 10 mg','cp','NOT IN THE pdf LIST or in wrong place');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Montelucaste','10 mg cp','SINGULAIR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Prednisolona','cp 5 mg; cp 20 mg; ampolas','SALU-DACORTINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fraxiparina','0,3 ml; 0,6 ml','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clorfeniramina','xp; cp; ampolas','ANTISTINA ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metilprednisolona','80 mg / 2 ml ampolas','DEPO- MEDROL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Prometazina','cp 25 mg; ampolas; gel','FENERGAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diprofilina','xp','NEUFIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cetotifeno ','xp; cap 1mg','ZADITEN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Budesonida/fumarato formoterol hidratado','spray','SYMBICORT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Budesonida ','cap 200 mcg inalacao oral','BUSONIDA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salmeterol via','inalatoria oral 25 mg','SEREVENT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salmeterol via','inalatoria oral','SEREVENT DISKUS');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Aminoflina','cp 225 mg','FILOTEMPO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dipropionato beclometasona nasal','','BECONASE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Beclometasona','oral spray','BECLO-ASMA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salbutamol','cap inala oral','VENTILAN ROTACAPS ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salbutamol','solucao para inalacao','VENTILAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salbutamol','spray oral','VENTILAN / BUTO ASMA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salbutamol','xp','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Salbutamol','cp 4 mg','VENTILA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Furoato mometasona ','creme; solucaoo','ELOCOM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Triancinolona','40 mg ampolas','KENALOG');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Butilescopolamina ','cp 10 mg; ampolas 20 mg','BUSCOPAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dimeticone(Simeticone) ','cp 42 mg; gotas 100 mg/ml','AERO OM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carvao vegetal 300 mg','','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cimetidina ','cp 400 mg; ampolas ','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pancreatina+dimeticone','cp','PANKREOFLAT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Domperidona','xp ; cp 10 mg','CINET');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloridrato mebeverina 200 mg','cp','DUSPATAL RETARD ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sulfasalazina','cp 500 mg','SALAZOPIRINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dimenidrinato 50 mg','cp','VOMIDRINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Loperamida','cp 2 mg','IMODIUM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metoclopramida ',' ampolas; cp 10 mg; gotas','PRIMPERAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Omeprazol','cap 20 mg','OMED');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ranitidina ','cp 150 mg; 300 mg','RANITINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidroxido aluminio+hidrox. Magnesio+dimeticone','cp','MAALOX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidroxido de aluminio','cp','PEPSAMAR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidroxido aluminio+hidrox. Magnesio','xp ','ANTI-ACIDO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sucralfato','cp 1g; saquetas','ULCERMIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sais de rehidratacao','oral saquetas','ORALIT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Neomicina+bacitracina','pomada','NEODERME');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oxido zinco+vita mina A e D+oleo figado peixe','','DERMOSYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Betametasona+acido salicilico','creme; solucao','PSODERMIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oxido zinco+oleo figado bacalhau','pomada','MITOSYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oxido zinco','pomada','HALIBUT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Calcio','xarope','CALCIGENOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Calcio+vitamina D3','cp 600 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lactogluconato calcio e carbonato calcio','cp efervescente','CALCIO SANDOZ');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido Alendronico','cp 70 mg','FOSAMAX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Alopurinol','cp 100 mg; cp 300 mg ','ZYLORIC/URIPRIM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Vitaminas+sais minerais+acido folico ','cp; xp','VITERRA/VICOMBIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Alfatocoferol','cp 150 mg','VARIMINE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Multivitaminas +minerais','cp','VITAMINA E');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cianocobalamina ','ampolas(vitamina B12)','OB12');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Vitamina B1+vit B6+vit 12 ','cp; ampolas','NEUROBION');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Piridoxina','cp 300 mg','BENADON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dissulfirano 500 mg','cp','TETRADIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Multivitamina','xarope','TONOSOL/MULTIVIT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Multivitaminas','gotas','PROTOVIT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Vitamina D','gotas','VIGANTOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido ascorbico (vitamina c )','cp; gotas','VITAMINA C');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Selenio+vit. A+vit C+E','cp','SELENIUM-ACE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amitriptilina ','cp 10 mg; cp 25 mg','ADT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Paroxetina','cp 20 mg','SEROXAT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carbonato litio','cp 400 mg','PRIADEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carbamazepina ','cp 200 mg; cp 400 mg ','TEGRETOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Biperideno','cp 2mg; ampolas','AKINETON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Olanzapina ','cp 5 mg; cp 10 mg ','ZYPREXA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Levomepromazina','cp 25 mg; cp 100 mg','NOZINAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fenintoina','cp 100 mg','HIDANTINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Vaiproato sodio ','cp 200 mg; cp 500 mg; xarope','DIPLEXIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ergotamina+cafeina+paracetamol','cp','MIGRETIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ergotamina+cafeina','cp','CAFERGOT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Haloperidol ','cp 5 mg; gotas; ampolas','HALDOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Risperdal ','cp 2 mg; solucao','RISPERDAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Imipramina','cp 25 mg','TOFRANIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clomipramina','cp 25 mg','ANAFRANIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clorpromazina ','cp 25 mg; cp 100 mg; ampolas ','LARGACTIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lorazepan','cp 1 mg; cp 2,5 mg','LORENIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clorodiazepoxido','cp 10 mg','PAXIUM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Valeriana','cp 45 mg','VALDISPERT');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Imunoglobulina humana anti-D','ampolas','D-GAN/RHOPHYLAC/');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Insulina humana lenta','ampolas','INSULATARD');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Insulina humana rapida','ampolas','ACTRAPID');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Latanoprost','colirio','XALATAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Latanoprost +timolol','colirio','XALACOM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloranfenicol','colirio; pomada oftalmica','CLOROCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dexametasona+neomicina','colirio','DEXAVAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hipromelose','colirio','DAVILOSE FORTE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dorzalamida','20 mg colirio','PROGLAU');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ciclopentolato','10 mg colirio','CICLOPLEGICEDOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hidroxipropilmetilcelulose','colirio','HIDROCIL FILAC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oloxacina','3 mg colirio','FLOXEDOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Diclofenac','colirio','VOLTAREN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Atropina','10 mg colirio','ATROPOCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acetozolamida','cp 250 mg','CARBINIB');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tropicamida','10 mg colirio','TROPICIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Prednisolona','colirio','FRISOLONA FORTE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oximetazolina','colirio','ALERJON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Timolol','0,5 colirio','TIMOGLAU');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oxibuprocaina','colirio','ANESTOCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Norfioxacina','colirio','CHIBROXOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Aciclovir','pomada oftalmica','ZOVIRAX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dexametasona','colirio','RONIC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Clotrimazol','colirio','DIOMICETE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Carbamero','gel oftalmico','VIDISIC GEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Bendazac de lisina','colirio','BENDALINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tetraciclina','pomada oftalmica','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('CromogIicato de sodio','colirio','FENOLIP');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fluormetalona','colirio  0,5 ml','FML LIQUIFILM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dexametasona+gentamicina','pomada oftalmica','DAXAMYTREX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dexametasona +gentamicina','colirio','DEXAMYTREX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pirenoxina','colirio','CLARVISAN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Gentamicina ','colirio; pomada oftalmica','GENTOCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Pilocarpina','colirio','PILOCARCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Drospirenona/Etinilestradiol','cp','YASMIN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Desogestrel/etilnhlestradiol','cp','MERCILON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acetato de ciproterona/etinilestradiol','cp','DIANE 35');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Etinilestradiol+gestodeno','cp','GYNERA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Etinilestradiol+levonorgestrel','cp','MICROGINON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Drospirenona/Etinilestradiol','cp 3 mg/0,2 mg','YAZ/YASMINELLE');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Levonorgestrel 1500 microgramas','cp','POSTINOR (PILULA DO DIA SEGUINTE0');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Glibenclamida','cp 5 mg','CLAMIBEN/EUGLUCOM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Metformina ','cp 500 mg; cp 850 mg; cp 1000 mg','RISIDOM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Glicazida ','cp 30 mg; cp 80 mg','DIAMICRON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acarbose','cp 50 mg','GLUCOBAY');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Peroxido benzilo','gel','BENZAC GEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Eritromicina+isotretinoina','gel','ISOTRENIN GEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Isotretinoina','gel','ISOTREX GEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Isotretinoina','cap 20 mg','ISOTREX');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ureia +pantenol','creme','CARMITOL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Oxido zinco+ac.salicilico+ac.borico+vitaminas','pasta','LAURODERME');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sulfato ferroso','cp 329,7 mg  cp','FERRO GRADUMET');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ferrol-acido folico','cp','FOLIFER');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido folico','cp 5 mg','FOLICIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Gluconato ferroso','xp','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ferro','gotas','FERRUM HAUSMANN');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Ferro','ampolas','FERCAYL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Acido aminocaproico','ampolas','EPSICAPROM');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloreto de potassio','cp 600 mg','');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fenilefrina','gotas 0,25 infantil','NEO-SINEFRINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fenilefrina','gotas 0,5 adulto','NEO-SINEFRINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cromoglicato de sodio','solucao nasal','FENOLIP');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dimetindeno+fenilefrina','spray nasal ','VIBROCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Dimetindeno+fenilefrina','gotas nasal','VIBROCIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Azelastina','solucao nasal','ALLERGODIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Budesonida','susp. Nasal','PULMICORT AQUA NASAL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Cloreto de sodio','gotas nasais','SORO FISIOLOGICO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fluocinolona+neomicina+polimixina','gotas auriculares','OTO-SYNALAR');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('diclorobenzeno +benzocaina+clorobutanol','gotas auricula','OTOCERIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Lactulose ','xarope','DUPHALAC');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Gelatina+glicerina','gel','BEBEGEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Tiras para determinagao glicemia','','BREEZ/ACCU-CHEK/ON CALL PLUS');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Amidotrizoato sodio amidotrizoato meglumina','solucao','GASTROGRAFINA');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('loxitalamato meglumina 50 ml','','TELEBRIX GASTRO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('lopromida 50 ml','','UTRAVIST 370');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sulfato de barbio uso rectal','','POLIBAR RAPID/ PRONTOBARIO COLON');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Sulfato de bario','','GASTRO BARIO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Fosfato dissodico hidratado+f.monossodico','solucao','PRECLINT/X-PREP');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('loxitalamato de meglumina 300mg/50 ml','','TELEBRIX GASTRO');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hexetina','solucao bucal','HEXTRIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Hexetina','spray bucal','COLU-HEXTRIL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Miconazol','gel oral','DAKTARIN GEL');
INSERT INTO "dcicv" ( "dcicv", "doze", "name") VALUES ('Nistatina','gotas','');