INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'AMOX', 'cap.250 e 500 mg; xp', 'Amoxicilina', 'Anti-infeciosos', 'Antibacterianos', 'Penicilinas');
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZYTROMAX ', 'cp 500 mg cp; xp', 'Azitromicina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'QUINOX', 'cp 500 mg', 'Ciprofloxacina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZOREF', 'cp 500 mg; xp', 'Cefuroxima ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'KLACID', 'cp 250 mg; 500 mg; xp', 'Claritromicina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CLAVEPEN/CLAVAMOX ', 'xp; cp 500 mg; ampolas ', 'Amoxicilina+acido clavulanico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLOXAPEN/FLOXIL', 'xp; cap 500 mg; ampolas', 'Flucloxacilina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TROBICIN /KIRIM', 'ampolas 2 gramas', 'Espectinomicina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ERITRAZON ', 'cp 500 mg; xp', 'Eritromicina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BACTRIM', 'cp 480 mg; cp 960 mg; xp', 'Cotrimoxazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FURADANTINA', 'cp 100 mg', 'Nitrofurantoina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BESFLOX', 'cp 400 mg', 'Norfloxacina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DALACIN C ', 'cp 150 mg', 'Clindamicina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DALACIN V', 'creme vaginal', 'Clindamicina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ECOZEN/ZOVIRAX/CICLOVIRAL', 'cp 200 mg; cp 400 mg; cp 800 mg; pomada oftalmica', 'Aciclovir ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZENTEL', 'cp 400 m; xp ', 'Albendazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PANTELMIN', 'cp 100 mg ; xp ', 'Mebendazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 600 mg', 'Praziquantel ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FASIGYN', 'cp 500 mg', 'Tinidazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLAGENTYL', 'cp 500 mg', 'Scnidazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'COMBANTRIN', 'xp 50 mg', 'Pirantel ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RESOCHINA ', 'cp 250 mg ', 'Cloroquina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MEFLOQUIN', 'cp 250 mg', 'Mefloquina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 250 mg', 'Cloroquina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FULCIN /GRISOVIN', 'cp 125 mg; cp 500 mg', 'Griseofulvina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FUNGONAX', 'cp 100 mg', 'Itraconazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CANESTEN', 'creme dermico 1%', 'Clotrimazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GYNO-CLOTRIN/GINO-CANESTEN', '1% creme ginecologco', 'Clotrimazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NALBIX/GINO-CANESTEN', 'ovulos vaginais', 'Clotrimazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CANESTEN', 'spray dermico', 'Clotrimazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'KANAZOL/NIZORAL', 'creme; cp 200 mg; shampoo', 'Cetoconazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SELENIX', 'shampoo', 'Sulfureto de selenio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PEVARYL', 'creme; locao ; pó', 'Nitrato de econazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TROSYD', 'creme dermico ; solucao ungueal', 'Tioconazol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BETADINE/DIODYNE', 'solucao vaginal; solucao dermitologica; pomada; colutor', 'lodopovidona ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLAGYL', 'ovulos 500 mg', 'Metronidazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'COLPOTROPHINE', 'cap vaginal 10 mg; creme vaginal', 'Promestrieno ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MICOZEN', 'creme', 'Nitrato de Miconazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NELEX', 'ovulos vaginais; locao', 'Policresuleno', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PAUSIGIN', 'creme vaginal', 'Estriol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'OMNIC', 'cp 4 microg', 'Tamsulosina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CAVERJECT', '10 micrg; 20 micrg ampolas', 'Alprostadil ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PROSCAR', 'cp 5 mg', 'Finasterida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'URISPAS', 'cp 200 mg', 'Cloridrato de flavoxato', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 1200 mg', 'Piracetam', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LIVIAL', 'cp 5 mg', 'Tibolona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SINEMET', 'cp 25/100 mg; 25/ 250 mg', 'Carbidopa +levodopa', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CASODEX', 'cp 50 mg', 'Bicalutamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZOLADEX', 'implante 8 mg', 'Goserrelina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'METERGIN', 'cp 12mg ', 'Metilergometrina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'METIBASOL/STRUMAZOL', 'cp 5 mg ; cp 10 mg', 'Tiamazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PROPYCIL', 'cp 50 mg', 'Propiltiouracilo', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LETTER', 'cp 100 micro', 'Levotiroxina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PROVERA', 'cp 5 mg', 'Medroxiprogesterona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PARLODEL', 'cp 5 mg', 'Bromocriptina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRIMOLUT', 'cp 10 mg', 'Acetato de noretisterona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DUFINE', 'cp 50 mg', 'Citrato de clomifeno', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'IMURAN', 'cp 25 mg', 'Azatioprina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'UTROGESTAN', 'cp 100 mg', 'Progesterona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ASPIN INFANTIL', 'cp 150 mg', 'Acido acetilsalicilico +vit c', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ASPIN', 'cp 500 mg', 'Acido acetilsalicilico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ASPEGIC', 'carteiras 500 mg; ampolas ', 'Acetilsalicilato de lisina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PANADOL / DAFALGAN / BEM-U-ROM', 'cp 500 mg; xp; sup; 125 mg; 250 mg; 1000 mg; eferv', 'Paracetamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BETASERC', 'cp 16 mg', 'Beta-histina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLUIMUCIL ', 'carteiras 200 mg; cp 600 mg', 'Acetilcisteina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DOLACEN/ VOLTAREN / BIOFENAC', 'cp 50 mg; 100 mg cap; suposit 100 mg; ampolas; gel', 'Diclofenac ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BRUFEN / DOLOMATE', 'xp; cp 200 mg; cp 400 mg; carteiras', 'Ibuprofeno', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'REUMACID/ INACID ', 'cap 25 mg; suposit 100 mg', 'Indometacina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'REUMON GEL/INALGIN', 'gel; creme;', 'Etofenamato ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'REUXEN/NAPROXIN', 'cp 250 mg; cp 500 mg; supos 250 mg; 500 mg', 'Naproxeno ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TRENTAL', 'cp 400 mg', 'Pentoxiflina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NOLOTIL', 'cp 575 mg', 'Metamizol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RELMUS', 'cp 4 mg; ampolas', 'Tiocolquicosido ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'REUMOXICAM', 'cp 20 mg', 'Piroxicam', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DAFLON/VENAFLON/DIOSMIN', 'cp 450 mg', 'Diosmina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VIARTRIL', 'ampol. 400 mg/3ml; po 1500 mg; cap 250 mg', 'Glucosamina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NADICLOX / FUCIDINE', 'pomada', 'Acido fusidico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ULTRAPROCT', 'suposito ', 'Pivalato fluocortolona+lidocaina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANUCET', 'pomada', 'Hidrocortisona+fenilefrinadrina+lidoc+tetra. ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CLAVERSAL', 'cp 500 mg', 'Messalazina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLINDIX', 'cp 5 mg; cp 20 mg', 'D initrato isossorbida ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'IMDUR', 'cp 60 mg', 'Mononitrato isossorbida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LASIX/NAQUA', 'cp 40 mg; ampolas', 'Furosemida ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ALDACTONE', 'cp 25 mg; cp 100 mg', 'Espironolactona ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HCT', 'cp 25 mg', 'Hidroclorotiazida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLUIDEMA', 'cp 5 mg', 'Indapamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NITRODERM TTS-5', '5 mg pensos transdermimicos', 'Nitroglicerina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NITRODERM TTS-10', '10 mg pensos transdermimicos', 'Nitroglicerina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ALDOMET', ' cp 250 mg', 'Metildopa', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ALDOMET FORTE', ' cp 500 mg', 'Metildopa', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', ' cp 250 mg', 'Ticlopidina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VASTAREL', 'cp 20 mg', 'Trimetazidina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'INDERAL', 'cp 10 mg; cp 40 mg', 'Propranolol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRITOR', 'cp 40 mg', 'Telmisartan', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRITOR PLUS ', 'cp 80 mg', 'Telmisartan', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TAREG/DIOVAN', 'cp 80 mg; cp 160 mg', 'Valsartan', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CO-TAREG/CO-DIOVAN', 'cp 5 mg', 'Valsartan 80 mg +hidroclorotiazida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CO-TAREG/CO-DIOVAN', 'cp 5 mg', 'Valsartan 160 mg +hidroclorotiazida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CORDARONE', 'cp 200 mg', 'Amiodarona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DILFAR', 'cp 180 mg', 'Diltiazem', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DILTIEM', 'cp 200 mg', 'Diltiazem', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANGIPINA/ ADALAT AP', 'cp 20 mg', 'Nifedipina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ADALAT CR 30', 'cp 30 mg', 'Nifedipina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ADALAT CR 60', ' cp 60 mg', 'Nifedipina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HIPOTENSIL', ' cp 25 mg', 'Captopril', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'APROVEL', 'cp 30 mg ', 'Irbesartan', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NORVASC', 'cp 5 mg; 10 mg', 'Amlodipina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 50 mg; 100 mg', 'Atenolol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ASPIRINA GR', 'cp 100 mg', 'Acido acetilsalicilico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CORIN', 'cp 100 mg', 'Acido acetilsalicilico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TROMALYT', 'cp 150 mg', 'Acido acetilsalicilico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CONCOR', 'cp 5 mg ; cp 10 mg', 'Bisoprolol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 10 mg; 20 mg', 'Lisinopril ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 25; cp 25 mg', 'Carvedilol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LOPRESOR', 'cp 100 mg', 'Metoprolol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 20 mg', 'Pravastatina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 20 mg', 'Sinvastatina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PLAVIX', 'cp 75 mg', 'Clopidogrel', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PERSANTIN', 'cp 75 mg', 'Dipiridamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SINTRON', 'cp 4 mg', 'Acenocumarol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VARFINE', 'cp 5 mg', 'Varfarina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LANOXIN ', 'cp 25 mg; xp', 'Digoxina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MAGNESONA', 'solucao oral', 'Magnesio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ATROVENT PA ', '20 micrg inalac.oral', 'Brometo ipratropio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ATROVENT UNIDOSE', 'inalac.nasal', 'Brometo ipratropio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CELESTONE', 'solucao oral', 'Betametasona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DIPROFOS DEPOT', 'ampolas 14 mg/2m1', 'Betametasona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DERMOVATE', 'creme; pomada; solucao', 'Propionato clebetasol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DAIVONEX', 'creme', 'Calcipotriol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LANTINGEN B ', 'adulto; infantil ', 'Suspensao oral lisados polibacterianos ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BRONCHO-VAXON', 'carteiras; cap inf; solug inf', 'Lisados polibacterianos liofilizado', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BRONCHO-VAXON', 'capsulas adulto', 'Lisados polibacterianos liofilizado', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZYRTEC', 'cp; xp', 'Cetirizina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'xp; cp', 'Loratadina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NOT IN THE pdf LIST or in wrong place', 'cp', 'Iclontelucaste 10 mg', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SINGULAIR', '10 mg cp', 'Montelucaste', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SALU-DACORTINA', 'cp 5 mg; cp 20 mg; ampolas', 'Prednisolona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', '3 ml; 6 ml', 'Fraxiparina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANTISTINA ', 'xp; cp; ampolas', 'Clorfeniramina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DEPO- MEDROL', '80 mg / 2 ml ampolas', 'Metilprednisolona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FENERGAN', 'cp 25 mg; ampolas; gel', 'Prometazina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NEUFIL', 'xp', 'Diprofilina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZADITEN', 'xp; cap 1mg', 'Cetotifeno ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SYMBICORT', 'spray', 'Budesonida/fumarato formoterol hidratado', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BUSONIDA', 'cap 200 mcg inalacao oral', 'Budesonida ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SEREVENT', 'inalatoria oral 25 mg', 'Salmeterol via', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SEREVENT DISKUS', 'inalatoria oral', 'Salmeterol via', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FILOTEMPO', 'cp 225 mg', 'Aminoflina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BECONASE', '', 'Dipropionato beclometasona nasal', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BECLO-ASMA', 'oral spray', 'Beclometasona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VENTILAN ROTACAPS ', 'cap inala oral', 'Salbutamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VENTILAN', 'solucao para inalacao', 'Salbutamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VENTILAN / BUTO ASMA', 'spray oral', 'Salbutamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'xp', 'Salbutamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VENTILA', 'cp 4 mg', 'Salbutamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ELOCOM', 'creme; solucaoo', 'Furoato mometasona ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'KENALOG', '40 mg ampolas', 'Triancinolona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BUSCOPAN', 'cp 10 mg; ampolas 20 mg', 'Butilescopolamina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'AERO OM', 'cp 42 mg; gotas 100 mg/ml', 'Dimeticone(Simeticone) ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', '', 'Carvao vegetal 300 mg', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 400 mg; ampolas ', 'Cimetidina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PANKREOFLAT', 'cp', 'Pancreatina+dimeticone', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CINET', 'xp ; cp 10 mg', 'Domperidona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DUSPATAL RETARD ', 'cp', 'Cloridrato mebeverina 200 mg', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SALAZOPIRINA', 'cp 500 mg', 'Sulfasalazina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VOMIDRINE', 'cp', 'Dimenidrinato 50 mg', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'IMODIUM', 'cp 2 mg', 'Loperamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRIMPERAN', ' ampolas; cp 10 mg; gotas', 'Metoclopramida ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'OMED', 'cap 20 mg', 'Omeprazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RANITINE', 'cp 150 mg; 300 mg', 'Ranitidina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MAALOX', 'cp', 'Hidroxido aluminio+hidrox. Magnesio+dimeticone', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PEPSAMAR', 'cp', 'Hidroxido de aluminio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANTI-ACIDO', 'xp ', 'Hidroxido aluminio+hidrox. Magnesio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ULCERMIN', 'cp 1g; saquetas', 'Sucralfato', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ORALIT', 'oral saquetas', 'Sais de rehidratacao', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NEODERME', 'pomada', 'Neomicina+bacitracina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DERMOSYL', '', 'Oxido zinco+vita mina A e D+oleo figado peixe', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PSODERMIL', 'creme; solucao', 'Betametasona+acido salicilico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MITOSYL', 'pomada', 'Oxido zinco+oleo figado bacalhau', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HALIBUT', 'pomada', 'Oxido zinco', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CALCIGENOL', 'xarope', 'Calcio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 600 mg', 'Calcio+vitamina D3', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CALCIO SANDOZ', 'cp efervescente', 'Lactogluconato calcio e carbonato calcio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FOSAMAX', 'cp 70 mg', 'Acido Alendronico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZYLORIC/URIPRIM', 'cp 100 mg; cp 300 mg ', 'Alopurinol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VITERRA/VICOMBIL', 'cp; xp', 'Vitaminas+sais minerais+acido folico ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VARIMINE', 'cp 150 mg', 'Alfatocoferol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VITAMINA E', 'cp', 'Multivitaminas +minerais', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'OB12', 'ampolas(vitamina B12)', 'Cianocobalamina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NEUROBION', 'cp; ampolas', 'Vitamina B1+vit B6+vit 12 ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BENADON', 'cp 300 mg', 'Piridoxina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TETRADIN', 'cp', 'Dissulfirano 500 mg', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TONOSOL/MULTIVIT', 'xarope', 'Multivitamina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PROTOVIT', 'gotas', 'Multivitaminas', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VIGANTOL', 'gotas', 'Vitamina D', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VITAMINA C', 'cp; gotas', 'Acido ascorbico (vitamina c )', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SELENIUM-ACE', 'cp', 'Selenio+vit. A+vit C+E', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ADT', 'cp 10 mg; cp 25 mg', 'Amitriptilina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SEROXAT', 'cp 20 mg', 'Paroxetina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRIADEL', 'cp 400 mg', 'Carbonato litio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TEGRETOL', 'cp 200 mg; cp 400 mg ', 'Carbamazepina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'AKINETON', 'cp 2mg; ampolas', 'Biperideno', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZYPREXA', 'cp 5 mg; cp 10 mg ', 'Olanzapina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NOZINAN', 'cp 25 mg; cp 100 mg', 'Levomepromazina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HIDANTINA', 'cp 100 mg', 'Fenintoina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DIPLEXIL', 'cp 200 mg; cp 500 mg; xarope', 'Vaiproato sodio ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MIGRETIL', 'cp', 'Ergotamina+cafeina+paracetamol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CAFERGOT', 'cp', 'Ergotamina+cafeina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HALDOL', 'cp 5 mg; gotas; ampolas', 'Haloperidol ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RISPERDAL', 'cp 2 mg; solucao', 'Risperdal ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TOFRANIL', 'cp 25 mg', 'Imipramina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANAFRANIL', 'cp 25 mg', 'Clomipramina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LARGACTIL', 'cp 25 mg; cp 100 mg; ampolas ', 'Clorpromazina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LORENIN', 'cp 1 mg; cp 5 mg', 'Lorazepan', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PAXIUM', 'cp 10 mg', 'Clorodiazepoxido', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VALDISPERT', 'cp 45 mg', 'Valeriana', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'D-GAN/RHOPHYLAC/', 'ampolas', 'Imunoglobulina humana anti-D', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'INSULATARD', 'ampolas', 'Insulina humana lenta', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ACTRAPID', 'ampolas', 'Insulina humana rapida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'XALATAN', 'colirio', 'Latanoprost', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'XALACOM', 'colirio', 'Latanoprost +timolol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CLOROCIL', 'colirio; pomada oftalmica', 'Cloranfenicol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DEXAVAL', 'colirio', 'Dexametasona+neomicina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DAVILOSE FORTE', 'colirio', 'Hipromelose', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PROGLAU', '20 mg colirio', 'Dorzalamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CICLOPLEGICEDOL', '10 mg colirio', 'Ciclopentolato', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HIDROCIL FILAC', 'colirio', 'Hidroxipropilmetilcelulose', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FLOXEDOL', '3 mg colirio', 'Oloxacina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VOLTAREN', 'colirio', 'Diclofenac', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ATROPOCIL', '10 mg colirio', 'Atropina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CARBINIB', 'cp 250 mg', 'Acetozolamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TROPICIL', '10 mg colirio', 'Tropicamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FRISOLONA FORTE', 'colirio', 'Prednisolona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ALERJON', 'colirio', 'Oximetazolina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TIMOGLAU', '5 colirio', 'Timolol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ANESTOCIL', 'colirio', 'Oxibuprocaina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CHIBROXOL', 'colirio', 'Norfioxacina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ZOVIRAX', 'pomada oftalmica', 'Aciclovir', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RONIC', 'colirio', 'Dexametasona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DIOMICETE', 'colirio', 'Clotrimazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VIDISIC GEL', 'gel oftalmico', 'Carbamero', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BENDALINA', 'colirio', 'Bendazac de lisina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'pomada oftalmica', 'Tetraciclina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FENOLIP', 'colirio', 'CromogIicato de sodio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FML LIQUIFILM', 'colirio  5 ml', 'Fluormetalona', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DAXAMYTREX', 'pomada oftalmica', 'Dexametasona+gentamicina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DEXAMYTREX', 'colirio', 'Dexametasona +gentamicina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CLARVISAN', 'colirio', 'Pirenoxina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GENTOCIL', 'colirio; pomada oftalmica', 'Gentamicina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PILOCARCIL', 'colirio', 'Pilocarpina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'YASMIN', 'cp', 'Drospirenona/Etinilestradiol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MERCILON', 'cp', 'Desogestrel/etilnhlestradiol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DIANE 35', 'cp', 'Acetato de ciproterona/etinilestradiol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GYNERA', 'cp', 'Etinilestradiol+gestodeno', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'MICROGINON', 'cp', 'Etinilestradiol+levonorgestrel', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'YAZ/YASMINELLE', 'cp 3 mg/2 mg', 'Drospirenona/Etinilestradiol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'POSTINOR (PILULA DO DIA SEGUINTE0', 'cp', 'Levonorgestrel 1500 microgramas', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CLAMIBEN/EUGLUCOM', 'cp 5 mg', 'Glibenclamida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'RISIDOM', 'cp 500 mg; cp 850 mg; cp 1000 mg', 'Metformina ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DIAMICRON', 'cp 30 mg; cp 80 mg', 'Glicazida ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GLUCOBAY', 'cp 50 mg', 'Acarbose', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BENZAC GEL', 'gel', 'Peroxido benzilo', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ISOTRENIN GEL', 'gel', 'Eritromicina+isotretinoina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ISOTREX GEL', 'gel', 'Isotretinoina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ISOTREX', 'cap 20 mg', 'Isotretinoina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'CARMITOL', 'creme', 'Ureia +pantenol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'LAURODERME', 'pasta', 'Oxido zinco+ac.salicilico+ac.borico+vitaminas', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FERRO GRADUMET', 'cp 7 mg  cp', 'Sulfato ferroso', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FOLIFER', 'cp', 'Ferrol-acido folico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FOLICIL', 'cp 5 mg', 'Acido folico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'xp', 'Gluconato ferroso', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FERRUM HAUSMANN', 'gotas', 'Ferro', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FERCAYL', 'ampolas', 'Ferro', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'EPSICAPROM', 'ampolas', 'Acido aminocaproico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'cp 600 mg', 'Cloreto de potassio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NEO-SINEFRINA', 'gotas 25 infantil', 'Fenilefrina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'NEO-SINEFRINA', 'gotas 5 adulto', 'Fenilefrina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'FENOLIP', 'solucao nasal', 'Cromoglicato de sodio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VIBROCIL', 'spray nasal ', 'Dimetindeno+fenilefrina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'VIBROCIL', 'gotas nasal', 'Dimetindeno+fenilefrina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'ALLERGODIL', 'solucao nasal', 'Azelastina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PULMICORT AQUA NASAL', 'susp. Nasal', 'Budesonida', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'SORO FISIOLOGICO', 'gotas nasais', 'Cloreto de sodio', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'OTO-SYNALAR', 'gotas auriculares', 'Fluocinolona+neomicina+polimixina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'OTOCERIL', 'gotas auricula', 'diclorobenzeno +benzocaina+clorobutanol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DUPHALAC', 'xarope', 'Lactulose ', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BEBEGEL', 'gel', 'Gelatina+glicerina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'BREEZ/ACCU-CHEK/ON CALL PLUS', '', 'Tiras para determinagao glicemia', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GASTROGRAFINA', 'solucao', 'Amidotrizoato sodio amidotrizoato meglumina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TELEBRIX GASTRO', '', 'loxitalamato meglumina 50 ml', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'UTRAVIST 370', '', 'lopromida 50 ml', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'POLIBAR RAPID/ PRONTOBARIO COLON', '', 'Sulfato de barbio uso rectal', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'GASTRO BARIO', '', 'Sulfato de bario', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'PRECLINT/X-PREP', 'solucao', 'Fosfato dissodico hidratado+f.monossodico', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'TELEBRIX GASTRO', '', 'loxitalamato de meglumina 300mg/50 ml', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'HEXTRIL', 'solucao bucal', 'Hexetina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'COLU-HEXTRIL', 'spray bucal', 'Hexetina', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'DAKTARIN GEL', 'gel oral', 'Miconazol', NULL, NULL, NULL);
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( '', 'gotas', 'Nistatina', NULL, NULL, NULL);

INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'Benzilpenicilina s?dica', 'Solu??o inject?vel, extempor?nea:1.000.000 U.I ; IM e IV (600 mg), Solu??o inject?vel, extempor?nea: 5.000.000 U.I ; I.M-I.V (3 g)', 'Benzilpenicilina s?dica', 'Anti-infeciosos', 'Antibacterianos', 'Penicilinas');
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'Benzatina', 'Suspens?o inject?vel, extempor?nea: 1.200.000U.I-I.M,Suspens?o inject?vel, extempor?nea: 2.400.000 U.I.-I.M( 1,44 g)', 'Benzilpenicilina Benzat?nica', 'Anti-infeciosos', 'Antibacterianos', 'Penicilinas');
INSERT INTO "dcicv" ( "dcicv", "doze", "name", "categoria", "grupo", "subgrupo") VALUES ( 'Proca?na', 'Suspens?o inject?vel: 1.000.000 U.I.-I.M ( 1 g )', 'Benzilpenicilina proca?nica', 'Anti-infeciosos', 'Antibacterianos', 'Penicilinas');